version: '3.8'

services:
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
        - 8000:8000
    stdin_open: true
    tty: true
    volumes:
        - ./backend/:/code/app

  frontend:
    build: ./frontend
    ports:
      - "1234:1234"
    stdin_open: true
    tty: true